# Generated by Django 4.2.20 on 2025-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
