# Generated by Django 4.2.20 on 2025-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_service_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingpackage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='photos.category'),
        ),
        migrations.DeleteModel(
            name='PackageFeature',
        ),
        migrations.DeleteModel(
            name='PricingPackage',
        ),
        migrations.DeleteModel(
            name='ServiceFeature',
        ),
    ]
