# Generated by Django 4.2.20 on 2025-08-24 16:42

import django.core.validators
from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_options_alter_photo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (alternative to uploading video file)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'webm']), photos.models.validate_video_size]),
        ),
    ]
