# Generated by Django 4.2.20 on 2025-10-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_aboutsection_heroslide_partner_sitesettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='description',
        ),
    ]
