# Generated by Django 4.2.20 on 2025-10-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_heroslide_cta_text_remove_heroslide_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='key_features',
            field=models.TextField(blank=True, help_text='Enter each feature on a new line. Example:\n4K/8K video production\nDrone cinematography\nProfessional lighting\nMulti-camera setups'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='photos.tag'),
        ),
    ]
