# Generated by Django 4.2.20 on 2025-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_service_key_features_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to display in home page gallery'),
        ),
    ]
