# Generated by Django 4.2.20 on 2025-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='mission',
            field=models.TextField(blank=True, help_text='Company mission statement'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision',
            field=models.TextField(blank=True, help_text='Company vision statement'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, help_text="e.g., 'Wedding Venues', 'Fashion Brands'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_type',
            field=models.CharField(blank=True, help_text="e.g., 'Wedding Clients', 'Corporate Client'", max_length=100, null=True),
        ),
    ]
