# Generated by Django 4.2.20 on 2026-09-09 23:17

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_aboutsection_mission_aboutsection_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(help_text='e.g. Lead Photographer', max_length=255)),
                ('photo', models.ImageField(upload_to='team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), photos.models.validate_image_size])),
                ('bio', models.TextField(blank=True, help_text='Short paragraph about this team member')),
                ('instagram', models.URLField(blank=True, help_text='Full Instagram profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='Full LinkedIn profile URL')),
                ('twitter', models.URLField(blank=True, help_text='Full Twitter / X profile URL')),
                ('facebook', models.URLField(blank=True, help_text='Full Facebook profile URL')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Auto-generated from title — keep URL-friendly', unique=True)),
                ('excerpt', models.TextField(help_text='Short teaser shown on cards (1–2 sentences)')),
                ('body', ckeditor.fields.RichTextField(help_text='Article body — supports rich text formatting')),
                ('cover_image', models.ImageField(help_text='Used for the card and hero image', upload_to='blog/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), photos.models.validate_image_size])),
                ('meta_title', models.CharField(blank=True, help_text='Leave blank to use post title', max_length=160)),
                ('meta_description', models.TextField(blank=True, help_text='Shown in Google snippet — aim for 150–160 chars')),
                ('published', models.BooleanField(default=False, help_text='Only published posts appear on the site')),
                ('show_on_home', models.BooleanField(default=True, help_text='Include in the blog cards on the home page')),
                ('published_at', models.DateTimeField(blank=True, help_text='Set a date to display on the post (does not auto-publish)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, help_text='Event album — photos shown in the article gallery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='photos.album')),
                ('extra_photos', models.ManyToManyField(blank=True, help_text='Individual photos to include alongside (or instead of) the album', related_name='blog_posts', to='photos.photo')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
